feat: 주문 상세 정보 생성 구현 #26
kakao-tech-campus-2nd-step3/Team14_BE pull request #29
Opened 2024-09-27 14:30 UTC by ajy9851

📌 관련 이슈
---
#26 
 주문 상세 정보 패키지 구조 및 엔티티 정의, 생성 까지 구현하였으나 다른 부분들은 아직 구현하지 못하였습니다.

✨ PR 내용
---
주문 상세 정보에는 참여자 정보(즉 여러 명의 Member)가 필요합니다.
따라서 Member와 다대다 연결을 위한 중간 테이블(연결 엔티티)인 OrderParticipant를 만들어뒀습니다.

2024-09-27 16:44 UTC, westzeroright commented on src/main/java/com/ordertogether/team14_be/order/details/controller/OrderDetailController.java
> +	}
`@RequiredArgsConstructor`사용하시면  코드를 간결하게 작성해볼 수 있을 것 같아요!

2024-09-27 16:44 UTC, westzeroright commented on src/main/java/com/ordertogether/team14_be/order/details/dto/create/CreateOrderDetailRequestDto.java
> +public class CreateOrderDetailRequestDto {
record가 뭔지 알아보고 dto를 만들 때 적용해보죠!

2024-09-27 17:16 UTC, westzeroright commented on src/main/java/com/ordertogether/team14_be/order/details/entity/OrderDetail.java
> +}
엔티티를 이렇게 설정하면 파티원마다 주문에 얼마의 결제금액을 각각 담당하는지 알 수 없을 것 같아요ㅜㅜ 엔티티는 월요일 회의 때 다시 이야기해봅시다!

2024-09-27 17:16 UTC, westzeroright commented on src/main/java/com/ordertogether/team14_be/order/details/service/OrderDetailService.java
> +			com.ordertogether.team14_be.member.persistence.MemberRepository memberRepository,
마지막에 파일을 확인하면서 코드의 간결과 통일성을 검토해보시면 좋을 것 같아요! 😳

2024-09-27 17:16 UTC, westzeroright commented on src/main/java/com/ordertogether/team14_be/order/details/service/OrderDetailService.java
> +	private final MemberRepository MemberRepository;
```java
private final MemberRepository memberRepository;
```
소문자로 변경해주세요!

2024-09-27 17:16 UTC, westzeroright commented on src/main/java/com/ordertogether/team14_be/order/details/service/OrderDetailService.java
> +		MemberRepository = memberRepository;
애만 왜 this 없어요ㅜㅜ

2024-09-27 17:16 UTC, westzeroright commented on src/main/java/com/ordertogether/team14_be/order/details/service/OrderDetailService.java
> +						.orElseThrow(() -> new IllegalArgumentException("방장 정보가 없습니다."));
맞춤형 예외 클래스를 만들어서 어떤 예외인지 명확하게 보이도록 하는 건 어떨까요?!

2024-09-28 03:18 UTC, nove1080 requested changes
개발한 기능에 대한 테스트 코드가 있었으면 좋겠습니다

2024-09-28 03:29 UTC, rbm0524 approved these changes
저는 영우님이 하셨던 말씀이랑 크게 다를건 없어서 approve했습니다 ERD는 월요일에 만나서 다시 점검할거니까 entity 부분은 이후에 수정하면 될 것 같아요

2024-09-28 03:29 UTC, rbm0524 commented on src/main/java/com/ordertogether/team14_be/order/details/service/OrderDetailService.java
> +		MemberRepository = memberRepository;
this가 없어도 변수명이 달라서 동작은 할 것 같아요. 그렇지만 영우님이 리뷰해주신 것처럼 memberRepository로 변수명이 바뀐다면 this가 필요해질 것 같아요

2024-09-28 03:29 UTC, rbm0524 commented on src/main/java/com/ordertogether/team14_be/order/details/controller/OrderDetailController.java
> +	@PostMapping
엔드 포인트 빠진 것 같아요 아직 결정을 못하신건가요?

2024-09-28 03:29 UTC, rbm0524 commented on src/main/java/com/ordertogether/team14_be/order/details/service/OrderDetailService.java
> +	private final MemberRepository MemberRepository;
OrderDetailService가 MemberRepository를 가지고 있는 것은 계층적으로 봤을 때 자연스러운 흐름인지 의문이 들어요. OrderDetailService가 MemberService에게  요청해서 필요한 정보를 받아오는 것은 어떨까요?

2024-10-02 13:16 UTC, ajy9851 commented on src/main/java/com/ordertogether/team14_be/order/details/controller/OrderDetailController.java
> +	@PostMapping
그 위에 공통적인 엔드 포인트 묶어둬서 이 부분엔 따로 적지 않았습니다!

2024-10-02 13:20 UTC, ajy9851 commented on src/main/java/com/ordertogether/team14_be/order/details/dto/create/CreateOrderDetailRequestDto.java
> +public class CreateOrderDetailRequestDto {
공부해볼게요 흑흑

2024-10-02 13:38 UTC, ajy9851 commented on src/main/java/com/ordertogether/team14_be/order/details/service/OrderDetailService.java
> +	private final MemberRepository MemberRepository;
막연히 서비스가 다른 서비스를 가지는게 더 이상하다 생각했는데 찾아보니 다른 레포지토리를 가지는게 더 좋지 않은건가보네요. 지금 MemberService에는 단순 조회하는 메서드가 없어서 이후에 만드시면 수정할게요

2024-10-03 01:25 UTC, ajy9851 commented on src/main/java/com/ordertogether/team14_be/order/details/service/OrderDetailService.java
> +	private final MemberRepository MemberRepository;
> OrderDetailService가 MemberRepository를 가지고 있는 것은 계층적으로 봤을 때 자연스러운 흐름인지 의문이 들어요. OrderDetailService가 MemberService에게 요청해서 필요한 정보를 받아오는 것은 어떨까요?

여러 글들 찾아 보니 정답은 없는 것 같습니다

2024-10-04 02:26 UTC, nove1080 approved these changes

2024-10-04 13:57 UTC, westzeroright approved these changes

2024-10-04 13:59 UTC, merged